### Numpy lec-02: Array Types, Dimension & Creation

In [1]:
import numpy as np

In [ ]:
# Array
Docstring: array(object,dtype=None, *,copy=True,order='K',subok=False,ndmin=0,like=None)
    
create_array-> '# syntax: np.array()

In [2]:
# Creating Numpy arrays
ls=[1,2,3,4]
arr=np.array(ls)
print(arr,type(arr))
arr

[1 2 3 4] <class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [3]:
l=[]
for i in range(10):
    l.append(i)
arr=np.array(l)
print(arr)
print('Dimension:',arr.ndim)

[0 1 2 3 4 5 6 7 8 9]
Dimension: 1


In [ ]:
# Types and Dimension of an array
1D array: [~]
2D array: [[~]]
3D array: [[[~]]]
    
arr_dimension_check-> 'syntax: arr_name.ndim
for_n-dimension array->  'use: ndmin=n

In [4]:
# lets try this
ar1=np.array([1,2,3])      # 1d array
print(ar1,'dimension:',ar1.ndim)
print('..........')

ar2=np.array([[1,2,3],[1,2,3]])        # 2d array
print(ar2,'dimension:',ar2.ndim)
print('..........')

ar3=np.array([[[1,2,3],[1,2,3],[1,2,3]]])       # 3d array
print(ar3,'dimension:',ar3.ndim)
print('..........')

arn=np.array([1,2,3],ndmin=5)           # n-d array
print(arn,'dimension:',arn.ndim)
arn

[1 2 3] dimension: 1
..........
[[1 2 3]
 [1 2 3]] dimension: 2
..........
[[[1 2 3]
  [1 2 3]
  [1 2 3]]] dimension: 3
..........
[[[[[1 2 3]]]]] dimension: 5


array([[[[[1, 2, 3]]]]])

### Numpy lec-03: Special Array

In [ ]:
# Creating Numpy array using Numpy function
# some special Numpy array
                                    '# syntax:
- Empty array                        np.empty(shape, dtype=float, order='C', *, like=None)
- Array with 0s                      np.zeros(shape, dtype=float, order='C', *, like=None)
- Array with 1s                      np.ones(shape, dtype=None, order='C', *, like=None)
- Array with range of elements       np.arange([start,] stop[, step,], dtype=None, *, like=None)
- Array diagonal elements having 1   np.eye(N, M=None, k=0, dtype=float, order='C', *, like=None)
- Array filled with num=n            np.full(shape, fill_value, dtype=None, order='C', *, like=None)

- Array with values that are spaced linearly in specified interval    '# np.linspace(start, stop, size)


In [5]:
# Empty array -return new array without initializing entries
import numpy as np
ar_emp=np.empty(0)
print(ar_emp)

[]


In [6]:
# Array with 0's -return new array filled with zeros
ar_zero=np.zeros(4)
ar_zero1=np.zeros((3,4))
print(ar_zero)
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# Array with 1's -return new array of given shape and type, filled with ones
ar_one=np.ones(4)
ar_one1=np.ones((3,4))
print(ar_one)
print(ar_one1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# Array with range of elements -return evenly spaced values within a given interval
ar_rn=np.arange(4)
print(ar_rn)

[0 1 2 3]


In [8]:
# Array diagonal elements having 1 -Return a 2-D array with ones on the diagonal and zeros elsewhere.
ar_dia=np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# Array filled with num=n
ar_full=np.full((3,3),5)
print(ar_full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [10]:
# Array with values that are spaced linearly in specified interval
arr=np.linspace(0,20,num=5)
print(arr)

[ 0.  5. 10. 15. 20.]


### Numpy lec-04: Random Function

In [ ]:
# Creating Numpy array with Random numbers
# Note: we call this f*n using random module
- rand()      
    '# np.random.rand(d0, d1, ..., dn)   -d0,d1,d2... takes to dimension
    -used to generate a random value between 0 and 1
- randn()
    '# np.random.randn(d0, d1, ..., dn)     -d0,d1,d2... takes to dimension
    -used to generate a random value close to 0
    -gives both +ve or -ve number
- ranf()
    '# np.random.ranf(num)
    -it is an alias of random_sample
    -used for doing random sampling in numpy
    -returns array of specified shape
    -fills random floats in the half open interval[0.0,1.0)
- randint()
    '# np.random.randint(low, high=None, size=None, dtype=int)                                             
    -used to generate random number in a given range

In [11]:
# lets try this
# rand()
import numpy as np
ar1=np.random.rand(3)     # 1d array
print(ar1)
ar2=np.random.rand(2,3)   # 2d array
print(ar2)

[0.00757526 0.2243544  0.07991993]
[[0.76519746 0.80622093 0.70165268]
 [0.63558196 0.47447487 0.10424133]]


In [12]:
# randn()
ar1=np.random.randn(3)        # 1d array
print(ar1)
ar2=np.random.randn(2,3)      # 2d array
print(ar2)

[-0.42279909 -1.87911395 -0.43639073]
[[0.06017208 0.66269554 0.57302833]
 [1.00631191 0.19572412 1.43131402]]


In [13]:
# ranf()
ar1=np.random.ranf(3)     
print(ar1)

[0.07526514 0.20592948 0.03935357]


In [14]:
# randint()
ar1=np.random.randint(1)     
print(ar1)
ar2=np.random.randint(1,5)     
print(ar2)
ar3=np.random.randint(1,10,4)     
print(ar3)

0
3
[6 4 1 6]
