### Numpy lec-14: Numpy Arrays Functions -I

In [1]:
import numpy as np

In [ ]:
# Numpy array functions:-I
Search array, Sort, Filter, Search Sorted array

In [ ]:
# Search array: search an array for a certain value, and return the indexes that get a match
# Where condition
- we can apply condition on array elements, sliced part, whole array etc.
    syntax: np.where(condition, value if True, value if False)
        
# Nested where condition
    syntax: np.where(condition, np.where(condition, value if True, value if False), value if False)
    syntax: np.where(condition, np.where(condition, np.where(condition, value if True, value if False),\n
                                         value if False), value if False)
# Note: 
- for nested condition 1st find 2nd condition and put it in 1st condition
- we can also apply where condition on an array by using: 
    'syntax: arr_name[condition]                                                           ---important---
    -here condition can be on array element or sliced array elements                

In [2]:
# lets try this -search array
# where condition in 1D array
arr1=np.arange(51)
x1=np.where(arr1%5==0)                          # modulo condition
x2=np.where((arr1>20)&(arr1<30), 1, 0)          # and operator
x3=np.where((arr1<10)|(arr1>40), 'yes', 'no')   # or operator
x4=np.where((arr1[::]%3==0), arr1 ,0)           # condition over slicing
print(x1)
print(x2)
print(x3)
print(x4)

(array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50], dtype=int64),)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
['yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes']
[ 0  0  0  3  0  0  6  0  0  9  0  0 12  0  0 15  0  0 18  0  0 21  0  0
 24  0  0 27  0  0 30  0  0 33  0  0 36  0  0 39  0  0 42  0  0 45  0  0
 48  0  0]


In [ ]:
# similarly: try for this
# where condition in 2D array

# where condition in 3D array


In [ ]:
# Sort array: return a sorted copy of an array
    '# syntax: np.sort(arr_name, axis=-1, kind=None, order=None)
    
# Filter array: 
- to get elements out of an existing array and creating a new array out of them
- here we will get all the filtered elements which I required
- give True for required elements and False for not required elements
- we can make 1D, 2D, 3D ...array also
    syntax: f=[True,False,True,True,False...]        # to get this filtered array pass it through the array
    
# Search Sorted array: find indices where elements should be inserted to maintain order
    '# syntax: np.searchsorted(arr_name, value, side='left', sorter=None)

In [3]:
# lets try this -sort array in 1D array
arr_n=np.array([87,25,63,75,73,39])          # sorting number
print(np.sort(arr_n))

arr_a=np.array(['D','R','T','A','M'])        # sorting alphabet
print(np.sort(arr_a))

# similarly try for 2D and 3D array

[25 39 63 73 75 87]
['A' 'D' 'M' 'R' 'T']


In [4]:
# lets try this -filter array in 1D array
arr2=np.array(['D','R','M','A','T'])
f=[True,True,False,False,True]
res=arr2[f]                    # to get filtered array pass it through the array
print(res)

# similarly try for 2D and 3D array

['D' 'R' 'T']


In [5]:
# lets try this -search sorted array in 1D array
arr3=np.array([2,4,5,7,8,9])
x1=np.searchsorted(arr3, 3)           # to know position of single elements
x2=np.searchsorted(arr3, [2,13,8])    # to know position of set of list of elements
print('index for 3:',x1)
print('indices for [2,13,8]:',x2)

# similarly try for 2D and 3D array

index for 3: 1
indices for [2,13,8]: [0 6 4]


In [6]:
# Ques.-find prime number in given range
def isprime(num):
    c=0
    for i in range(1,num+1):
        if num%i==0:
            c+=1
    if c==2:
        return True
    else:
        return False

arr=np.arange(101)
x=[]
for i in arr:
    if isprime(i):
        x.append(i)
print(x)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


### Numpy lec-15: Numpy Arrays Functions -II

In [ ]:
# Numpy array functions:-II
Shuffle, Unique, Resize, Flatten, Ravel

In [ ]:
# Shuffle: 
- to shuffle the array
- multi-dimensional arrays are only shuffled along the first axis
    '# syntax: np.random.shuffle(arr_name)

# Unique:
- to get the unique elements of an array
- to get 1st index num of unique element
- to get count of each element
'# syntax: np.unique(arr_name, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)
    
# Resize:
- return a new array with the specified shape given in tuple
    '# np.resize(arr_name, (new_shape))

In [7]:
# lets try this  -in 1D array                        ---ask? -reference variable why and why not--------
# shuffle
a1=np.array([1,2,3,4,5,6,7,8,9])
np.random.shuffle(a1)
print(a1)

# unique
a2=np.array([2,4,6,3,4,5,3,4,5])
x2=np.unique(a2,return_index=True,return_counts=True)
print(x2)

# resize
a3=np.array([3,2,5,4,6,8,7,9])
x3=np.resize(a3,(2,4))
print(x3)

[1 8 6 7 5 9 4 2 3]
(array([2, 3, 4, 5, 6]), array([0, 3, 1, 5, 2], dtype=int64), array([1, 2, 3, 2, 1], dtype=int64))
[[3 2 5 4]
 [6 8 7 9]]


In [ ]:
# Flatten:  
- return a copy of the array collapsed into one dimension
- order: {'C','F','A','K'}  -by default 'C'     -order is optional
    C -to flatten in row-major(C-style) order
    F -to flatten in column-major(Fortran-style) order
    A -to flatten in column-major order if 'a' is Fortran *contiguous* in memory, row-major order otherwise
    K -to flatten 'a' in the order the elements occur in memory
    '# syntax: arr_name.flatten(order='C')

# Ravel:                                                                ---ask? use of order A & K---
- return a contiguous flattened array
    '# syntax: np.ravel(arr_name, order='C')                             

In [8]:
# lets try this  -in 1D array
a4=np.arange(1,10).reshape(3,3)
print(a4)

print('........flatten......')      # flatten
x4=a4.flatten()                     # by default order=C
x5=a4.flatten(order='F')
print(x4,'\n',x5)

print('.........ravel........')      # ravel
x6=np.ravel(a4)
x7=np.ravel(a4,order='F')
print(x6,'\n',x7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
........flatten......
[1 2 3 4 5 6 7 8 9] 
 [1 4 7 2 5 8 3 6 9]
.........ravel........
[1 2 3 4 5 6 7 8 9] 
 [1 4 7 2 5 8 3 6 9]


### Numpy lec-16: Insert & Delete Functions Numpy Arrays

In [ ]:
# Insert function in Numpy array
- insert values along the given axis before the given indices
- while inserting, values should must matches with the array
- while inserting multiple elements take care of brackets (specially in append)
    '# syntax: np.insert(arr_name, indices(a,b,c..), values, axis=None)    -to insert integers values
    '# syntax: np.append(arr_name, values, axis=None)                      -to append integers/float values
    
# NOTE:
    - to take sliced indexing use: np.s_[::,::,::,...]

In [9]:
# lets try this   -using insert in 1D array
arr1=np.arange(1,10)
x1=np.insert(arr1,5,50)
x2=np.insert(arr1,(0,9),50)
print(x1,'\n',x2)

[ 1  2  3  4  5 50  6  7  8  9] 
 [50  1  2  3  4  5  6  7  8  9 50]


In [10]:
# lets try this   -using insert in 2D array
arr2=np.arange(1,7).reshape(2,3)
print(arr2)

x1=np.insert(arr2,2,50,axis=0)              # inserting an element along axis=0
x2=np.insert(arr2,2,50,axis=1)              # inserting an element along axis=1
print(x1,'\n',x2) 

x3=np.insert(arr2,2,[25,50,75],axis=0)      # inserting multiple element along axis=0
x4=np.insert(arr2,2,[25,50],axis=1)         # inserting multiple element along axis=1
print(x3,'\n',x4)

# similarly can try for 3D array

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [50 50 50]] 
 [[ 1  2 50  3]
 [ 4  5 50  6]]
[[ 1  2  3]
 [ 4  5  6]
 [25 50 75]] 
 [[ 1  2 25  3]
 [ 4  5 50  6]]


In [11]:
# lets try this   -using append in 1D array
arr1=np.arange(1,10)
x1=np.append(arr1,5.5)
print(x1)

# lets try this   -using append in 2D array
arr2=np.arange(1,7).reshape(2,3)
x2=np.append(arr2,[[25,50,75]],axis=0)            # take care of brackets while inserting multiple element
x3=np.append(arr2,[[25],[50]],axis=1)             # take care of brackets while inserting multiple element
print(x2,'\n',x3)

# similarly can try for 3D array

[1.  2.  3.  4.  5.  6.  7.  8.  9.  5.5]
[[ 1  2  3]
 [ 4  5  6]
 [25 50 75]] 
 [[ 1  2  3 25]
 [ 4  5  6 50]]


In [ ]:
# Delete function in Numpy array
- return a new array with sub-arrays along an axis deleted
    '# syntax: np.delete(arr_name, indices(a,b,c...), axis=None)
    
# NOTE:
    - to take sliced indexing use: np.s_[::,::,::,...]

In [12]:
# lets try this           -in 1D array
a1=np.array([1,2,3,4,5,6,7,8,9])
d1=np.delete(a1,4)                    # to delete single element
d2=np.delete(a1,(0,1,8))              # to delete particular index elements
d3=np.delete(a1,np.s_[2:7])           # to delete sliced elements
print(d1,'\n',d2,'\n',d3)

[1 2 3 4 6 7 8 9] 
 [3 4 5 6 7 8] 
 [1 2 8 9]
