### Numpy lec-05: Data Types in Numpy Array

In [1]:
import numpy as np

In [ ]:
# Data types in Numpy array
bool_
int_
float_
complex_
intc, intp, int8, int16, int32, int64
uint8, uint16, uint32, uint64
float16, float32, float64
complex64, complex128

# how to find data type in numpy array
- to use above data types: 
    '# use syntax: dtype=np.data_type          eg. dtype=np.int
- to know data types of an array
    '# syntax: arr_name.dtype              

In [2]:
# lets try this
arr=np.array([])                       # empty
print(arr,'Data type:',arr.dtype)
arr1=np.array([1,2,3])                 # integer
print(arr1,'Data type:',arr1.dtype)
arr2=np.array([2.5,6.8])               # float
print(arr2,'Data type:',arr2.dtype)
arr3=np.array([True])                  # bool
print(arr3,'Data type:',arr3.dtype)
arr4=np.array([2+3j])                  # complex
print(arr4,'Data type:',arr4.dtype)
arr5=np.array(['D','H','A','R','M'])   # string
print(arr5,'Data type:',arr5.dtype)

arr6=np.array([1,True,2.5,'D',2+3j])   # mixed
print(arr6,'Data type:',arr6.dtype)

[] Data type: float64
[1 2 3] Data type: int32
[2.5 6.8] Data type: float64
[ True] Data type: bool
[2.+3.j] Data type: complex128
['D' 'H' 'A' 'R' 'M'] Data type: <U1
['1' 'True' '2.5' 'D' '(2+3j)'] Data type: <U64


In [ ]:
# Data types as function -typecasting data type
-characters used to represent dtype in Numpy
i- integer
b- boolean
u- unsigned integer
f- float
c- complex float
m- timedelta
M- datetime
O- object
S- string
U- Unicode string
V- (void)
        '# syntax to use: dtype="f"      -to convert into float

In [3]:
# lets try this
arr1=np.array([1,2,3],dtype=np.int8)                 
print(arr1,'Data type:',arr1.dtype)

# type casting
arr2=np.array([1,2,3],dtype="f")                 
print(arr2,'Data type:',arr2.dtype)

print('..........')
# data type as function
arr3=np.array([1,2,3])  
new=np.complex64(arr3)

print(arr3,'Data type:',arr3.dtype)
print(new,'Data type:',new.dtype)

[1 2 3] Data type: int8
[1. 2. 3.] Data type: float32
..........
[1 2 3] Data type: int32
[1.+0.j 2.+0.j 3.+0.j] Data type: complex64


In [5]:
# direct data type typecasting 
# arr_name.astype() -copy of the array, cast to a specified type
    -use syntax: new=arr_name.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

arr1=np.array([1,2,3])      
new1=arr1.astype(float)
print(arr1,'Data type:',arr1.dtype)
print(new1,'Data type:',new1.dtype)

[1 2 3] Data type: int32
[1. 2. 3.] Data type: float64


### Numpy lec-06: Arithmetic Operations in Numpy

In [ ]:
# Arithematic Operations
a+b -np.add(a,b)
a-b -np.subtract(a,b)
a*b -np.multiply(a,b)
a/b -np.divide(a,b)
a//b -
a%b -np.mod(a,b)
a**b -np.power(a,b)
1/a -np.reciprocal(a)

In [6]:
# lets try this
import numpy as np
arr=np.array([1,2,3,4])

print(arr+5)
print(arr-1)
print(arr*2)
print(arr/2)
print(arr//2)
print(arr%2)
print(arr**2)
print(1/arr)

[6 7 8 9]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[1 0 1 0]
[ 1  4  9 16]
[1.         0.5        0.33333333 0.25      ]


In [7]:
# arithmatic operation on 1D array
arr1=np.array([5,4,3,2])
arr2=np.array([1,2,3,4])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(arr1%arr2)
print(arr1**arr2)

[6 6 6 6]
[ 4  2  0 -2]
[5 8 9 8]
[5.  2.  1.  0.5]
[5 2 1 0]
[0 0 0 2]
[ 5 16 27 16]


In [8]:
# arithmatic operation using numpy function
arr1=np.array([5,4,3,2])
arr2=np.array([1,2,3,4])

print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.mod(arr1,arr2))
print(np.power(arr1,arr2))
print(np.reciprocal(arr2))

[6 6 6 6]
[ 4  2  0 -2]
[5 8 9 8]
[5.  2.  1.  0.5]
[0 0 0 2]
[ 5 16 27 16]
[1 0 0 0]


In [9]:
# arithmatic operation on 2D array
arr21=np.array([[1,2,3,4],[2,3,4,5]])
arr22=np.array([[5,4,3,2],[4,3,2,1]])

print(arr21+arr22)
print(arr21-arr22)
print(arr21*arr22)
print(arr21/arr22)
print(arr21//arr22)
print(arr21%arr22)
print(arr21**arr22)
print(1/arr21)

[[6 6 6 6]
 [6 6 6 6]]
[[-4 -2  0  2]
 [-2  0  2  4]]
[[5 8 9 8]
 [8 9 8 5]]
[[0.2 0.5 1.  2. ]
 [0.5 1.  2.  5. ]]
[[0 0 1 2]
 [0 1 2 5]]
[[1 2 0 0]
 [2 0 0 0]]
[[ 1 16 27 16]
 [16 27 16  5]]
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]]


In [ ]:
# arithmatic operation on 3D array -lets try this


### Numpy lec-07: Arithmetic Functions in Numpy

In [ ]:
# Arithmetic Functions
                '# syntax:
np.min(x)        np.min(a,axis=None)                                       -to get min
np.max(x)        np.max(a,axis=None)                                       -to get max
np.argmin(x)     np.argmin(a,axis=None,out=None, *,keepdims=<no value>)    -to get index of min
np.argmax(x)     np.argmax(a,axis=None,out=None, *,keepdims=<no value>)    -to get index of max
np.sqrt(x)       np.sqrt(*args, **kwargs)                                  -to get squareroot
np.sin(x)        np.sin(*args, **kwargs)
np.cos(x)        np.cos(*args, **kwargs)
np.cumsum(x)     np.cumsum(a, axis=None, dtype=None, out=None)             -to find cumulative sum as we do in statistics
# NOTE:
    - axis are used while dealing with 2D or above dimension arrays         '---------must remember--------

In [10]:
# lets try this
import numpy as np
arr=np.array([16,4,25,1,9,36])

print('Min:',np.min(arr),'idx_min:',np.argmin(arr))
print('Max:',np.max(arr),'idx_max:',np.argmax(arr))

Min: 1 idx_min: 3
Max: 36 idx_max: 5


In [11]:
arr=np.array([1,2,3])
print('Square root:',np.sqrt(arr))
print('sin value:',np.sin(arr))
print('cos value:',np.cos(arr))
print('cumulative sum:',np.cumsum(arr))

Square root: [1.         1.41421356 1.73205081]
sin value: [0.84147098 0.90929743 0.14112001]
cos value: [ 0.54030231 -0.41614684 -0.9899925 ]
cumulative sum: [1 3 6]


In [14]:
# arithmatic function on 2D array
# Note: axis-0: for columns, axis-1: for rows

arr=np.array([[6,0,4,9],   # -> rows 
              [5,2,7,1]])  # ^columns

print('Min:',np.min(arr))
print('Min:',np.min(arr,axis=1))       # min along rows
print('Min:',np.min(arr,axis=0))       # min along columns
print('............')
print('Max:',np.max(arr))
print('Max:',np.max(arr,axis=1))       # max along rows
print('Max:',np.max(arr,axis=0))       # max along columns

print(np.sqrt(arr),'......Square root:')

Min: 0
Min: [0 1]
Min: [5 0 4 1]
............
Max: 9
Max: [9 7]
Max: [6 2 7 9]
[[2.44948974 0.         2.         3.        ]
 [2.23606798 1.41421356 2.64575131 1.        ]] ......Square root:
