### Numpy lec-08: Shape and Reshape in Numpy Array

In [1]:
import numpy as np

In [3]:
# Shape in Numpy array  -it gives shape type of an array in tuple, in string format, specifying the length
    '# syntax: np.shape(arr_name)

arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],
               [3,4,5]])
arr3=np.array([[[1,2,3],[3,4,5]],
               [[2,3,4],[4,5,6]],
               [[3,4,5],[5,6,7]]])
print(arr1,'shape:',np.shape(arr1),'dimendion:',arr1.ndim)      
print(arr2,'shape:',np.shape(arr2),'dimendion:',arr2.ndim)
print(arr3,'shape:',np.shape(arr3),'dimendion:',arr3.ndim)

[1 2 3] shape: (3,) dimendion: 1
[[1 2 3]
 [3 4 5]] shape: (2, 3) dimendion: 2
[[[1 2 3]
  [3 4 5]]

 [[2 3 4]
  [4 5 6]]

 [[3 4 5]
  [5 6 7]]] shape: (3, 2, 3) dimendion: 3


In [4]:
# NOTE: 
# to check dimension                      -use: arr_name.ndim
# to get/have dimension                   -use: ndmin=n                    eg.-1,2,3,4...
# to check shape of an array              -use: np.shape(arr_name)  
# to change/reshape the shape of an array -use: array_name.reshape(shape)  eg.-(l,m,n,.....)

arr=np.array([1,2,3,4],ndmin=4)
print(arr,'shape:',np.shape(arr),'dimension:',arr.ndim)

print('.............')

arr=np.array([1,2,3,4],ndmin=4).reshape(2,2)
print(arr,'shape:',np.shape(arr),'dimension:',arr.ndim)

[[[[1 2 3 4]]]] shape: (1, 1, 1, 4) dimension: 4
.............
[[1 2]
 [3 4]] shape: (2, 2) dimension: 2


In [ ]:
# Reshape the Numpy array     -returns an array containing the same data with a new shape
    '# syntax: arr_name.reshape(shape, order='C')

# Note: 
- take care of num of elements while reshaping an array
- we can even change the dimension of an array while reshaping
- eg. (3,3,4) -it means we get 3-row, 3-row and 4-column/elements

In [5]:
# 1D array
arr1=np.array([1,2,3,4,5,6])
x=arr1.reshape(2,3)
print(x,'shape:',np.shape(x),'dimension:',x.ndim)

# is same as
arr1=np.array([1,2,3,4,5,6]).reshape(3,2)
print(arr1,'shape:',np.shape(arr1),'dimension:',arr1.ndim)

[[1 2 3]
 [4 5 6]] shape: (2, 3) dimension: 2
[[1 2]
 [3 4]
 [5 6]] shape: (3, 2) dimension: 2


In [6]:
# 2D array
arr2=np.array([[1,2,3],
               [3,4,5]])
x=arr2.reshape(3,2)
print(x,'shape:',np.shape(x),'dimension:',x.ndim)

# is same as
arr2=np.array([[1,2,3],
               [3,4,5]]).reshape(2,3)
print(arr2,'shape:',np.shape(arr2),'dimension:',arr2.ndim)

[[1 2]
 [3 3]
 [4 5]] shape: (3, 2) dimension: 2
[[1 2 3]
 [3 4 5]] shape: (2, 3) dimension: 2


In [7]:
# 3D array
arr3=np.array([[[1,2,3],[3,4,5]],
               [[2,3,4],[4,5,6]],
               [[3,4,5],[5,6,7]]])
x=arr3.reshape(2,3,3)
print(x,'shape:',np.shape(x),'dimension:',x.ndim)

# is same as
arr3=np.array([[[1,2,3],[3,4,5]],
               [[2,3,4],[4,5,6]],
               [[3,4,5],[5,6,7]]]).reshape(3,2,3)
print(arr3,'shape:',np.shape(arr3),'dimension:',arr3.ndim)


[[[1 2 3]
  [3 4 5]
  [2 3 4]]

 [[4 5 6]
  [3 4 5]
  [5 6 7]]] shape: (2, 3, 3) dimension: 3
[[[1 2 3]
  [3 4 5]]

 [[2 3 4]
  [4 5 6]]

 [[3 4 5]
  [5 6 7]]] shape: (3, 2, 3) dimension: 3


In [8]:
# Note: Remember this for converting any array into 1D array using reshape

arr3=np.array([[[1,2,3],[3,4,5]],
               [[2,3,4],[4,5,6]],
               [[3,4,5],[5,6,7]]])
x=arr3.reshape(-1)
print(x,'dimension:',np.shape(arr3),'dimension:',x.ndim)

[1 2 3 3 4 5 2 3 4 4 5 6 3 4 5 5 6 7] dimension: (3, 2, 3) dimension: 1


### Numpy lec-09: Broadcasting Numpy Array

In [ ]:
# Broadcasting in Numpy array   -for arithmetic array operations
- either same dimension
- or compare shape from right side '(should must have atleast min 1 in any one)

    eg. (1*3)+(3*1)=(3*3)   -we get (3*3)matrix/array 

In [9]:
# lets try this
arr1=np.array([3,4,5]).reshape(1,3)
arr2=np.array([1,2,3]).reshape(3,1)

print(arr1,'shape:',np.shape(arr1),'dimension:',arr1.ndim)
print(arr2,'shape:',np.shape(arr2),'dimension:',arr2.ndim)

arr=arr1+arr2
print('Add\n',arr,'shape:',np.shape(arr),'dimension:',arr.ndim)

print('Substract\n',arr1-arr2)
print('Multiply\n',arr1*arr2)
print('Divide\n',arr1/arr2)
print('Floor div\n',arr1//arr2)
print('Modulo\n',arr1%arr2)
print('Power\n',arr1**arr2)

[[3 4 5]] shape: (1, 3) dimension: 2
[[1]
 [2]
 [3]] shape: (3, 1) dimension: 2
Add
 [[4 5 6]
 [5 6 7]
 [6 7 8]] shape: (3, 3) dimension: 2
Substract
 [[2 3 4]
 [1 2 3]
 [0 1 2]]
Multiply
 [[ 3  4  5]
 [ 6  8 10]
 [ 9 12 15]]
Divide
 [[3.         4.         5.        ]
 [1.5        2.         2.5       ]
 [1.         1.33333333 1.66666667]]
Floor div
 [[3 4 5]
 [1 2 2]
 [1 1 1]]
Modulo
 [[0 0 0]
 [1 0 1]
 [0 1 2]]
Power
 [[  3   4   5]
 [  9  16  25]
 [ 27  64 125]]


### Numpy lec-10: Indexing and Slicing

In [ ]:
# Indexing in Numpy array   -address of an element
    '# syntax: arr_name([i][j][k]...)  or arr_name([i,j,k,...])

# 1D array
  0 1 2 3 4 5  -> indexing
 [9 8 7 6 5 4]
 -6-5-4-3-2-1   -> reverse indexing
    
# 2D array
- element address   2D array indexing
    0  1  2           0 1 2 3    -> indexing
0  00 01 02       0 [[9 8 7 6]  -4
1  10 11 12       1  [8 7 6 5]  -3
2  20 21 22       2  [7 6 5 4]  -2
3  30 31 32       3  [6 5 4 3]] -1
                     -4-3-2-1    -> reverse indexing
# 3D array
             C1  C2  C3            0  1  2       -> indexing
R1(0) R1(0) 000 001 002    0 0 [[[11 12 13]   -3 -3   
      R2(1) 010 011 012      1   [14 15 16]      -2
      R3(2) 020 021 022      2   [17 18 19]]     -1
                               
R2(1) R1(0) 100 101 102    1 0  [[20 21 22]   -2 -3
      R2(1) 110 111 112      1   [23 24 25]      -2
      R3(2) 120 121 122      2   [26 27 28]]     -1

R3(2) R1(0) 200 201 202    2 0  [[29 30 31]   -1 -3
      R2(1) 210 211 212      1   [32 33 34]      -2
      R3(2) 220 221 222      2   [35 36 37]]]    -1
                                  -3 -2 -1      -> reverse indexing

In [10]:
# lets try this 
# 1D array indexing
arr1=np.array([9,8,7,6])
print(arr1[1])    # to get 8
print(arr1[-1])   # to get 6

8
6


In [11]:
# 2D array indexing
arr2=np.array([[9,8,7],
               [4,5,6]])
print(arr2[0][1])   # to get 8
print(arr2[0])      # to get [9 8 7]
print(arr2[0,1])    # to get 8
print(arr2[1,-1])   # to get 6

8
[9 8 7]
8
6


In [12]:
# 3D array indexing
arr3=np.array([[[9,8,7],
                [6,4,5],
                [2,3,1]]])

print(arr3[0][0][1])     # to get 8
print(arr3[0])
print(arr3[0,1])         # to get [6 4 5]
print(arr3[0,0,1])       # to get 8
print(arr3[0,1,1])       # to get 4
print(arr3[-1,-1,-1])    # to get 1

8
[[9 8 7]
 [6 4 5]
 [2 3 1]]
[6 4 5]
8
4
1


In [ ]:
# Slicing in Numpy array  -printing parts of an array
- slicing is done by index number of the elements
- for slicing >1D array it is done by dimension wise
    '# syntax: arr_name[start:stop:step, start:stop:step, start:stop:step,............]
    '# syntax: arr_name[start:stop:step][start:stop:step][start:stop:step][............]
    

In [13]:
# lets try this
# 1D array slicing
arr1=np.array([9,8,7,6,5,4,3,2,1])
            #  0 1 2 3 4 5 6 7 8 
print('All:',arr1)
print('All:',arr1[:])
print('Till 4:',arr1[:6])         # initial slicing
print('8 to 3:',arr1[1:7])        # mid slicing
print('5 to last:',arr1[4:])      # end slicing
print('.............')
print('Reverse:',arr1[-1::-1])    # reverse iteration
print('Reverse:',arr1[::-1])
print('Till 2nd last:',arr1[:-1:])
print('.............')
print('Alternate:',arr1[::2])     # use of step
print('Alternate:',arr1[1:7:2])
print('Alternate:',arr1[::-2])    # reverse stepping

All: [9 8 7 6 5 4 3 2 1]
All: [9 8 7 6 5 4 3 2 1]
Till 4: [9 8 7 6 5 4]
8 to 3: [8 7 6 5 4 3]
5 to last: [5 4 3 2 1]
.............
Reverse: [1 2 3 4 5 6 7 8 9]
Reverse: [1 2 3 4 5 6 7 8 9]
Till 2nd last: [9 8 7 6 5 4 3 2]
.............
Alternate: [9 7 5 3 1]
Alternate: [8 6 4]
Alternate: [1 3 5 7 9]


In [14]:
# 2D array slicing
arr2=np.array([[9,8,7,6],
               [4,5,6,7],
               [0,1,3,2]])
print('shape:',arr2.shape,'dimension:',np.ndim(arr2))

print('five:',arr2[1,1])
print(arr2[::,::])
print('..........')
print('1st row:',arr2[0])
print('2nd column:',arr2[:,1])
print('mid element:',arr2[1:2,1:3])
print('outer element:',arr2[0],arr2[2],arr2[:,0],arr2[:,3])
print('.........')
print(arr2[-1,-1])        # reverse
print(arr2[-1])
print(arr2[:,-1])
print(arr2[::-1,::-1])

shape: (3, 4) dimension: 2
five: 5
[[9 8 7 6]
 [4 5 6 7]
 [0 1 3 2]]
..........
1st row: [9 8 7 6]
2nd column: [8 5 1]
mid element: [[5 6]]
outer element: [9 8 7 6] [0 1 3 2] [9 4 0] [6 7 2]
.........
2
[0 1 3 2]
[6 7 2]
[[2 3 1 0]
 [7 6 5 4]
 [6 7 8 9]]


In [15]:
# 3D array slicing
arr3=np.arange(11,38).reshape(3,3,3)

print('shape:',arr3.shape,'dimension:',np.ndim(arr3))
print(arr3[::,::,::])

# NOTE: arr3[::][::][::] or arr3[::,::,::] or arr3[:,:,:]  -these are the same

shape: (3, 3, 3) dimension: 3
[[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[29 30 31]
  [32 33 34]
  [35 36 37]]]


In [16]:
arr3=np.arange(11,38).reshape(3,3,3)

print(arr3[1,:,:])
print(arr3[:,1,:])
print(arr3[:,:,1])

[[20 21 22]
 [23 24 25]
 [26 27 28]]
[[14 15 16]
 [23 24 25]
 [32 33 34]]
[[12 15 18]
 [21 24 27]
 [30 33 36]]


In [17]:
arr3=np.arange(11,38).reshape(3,3,3)

print(arr3)
print(arr3[0,0,0])                           # access 1st most element
print(arr3[0,0,0],arr3[1,1,1],arr3[2,2,2])   # accessing diagonal elements

[[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[29 30 31]
  [32 33 34]
  [35 36 37]]]
11
11 24 37


In [18]:
arr3=np.array([[[11,12,13],[14,15,16],[17,18,19]],                   
               [[20,21,22],[23,24,25],[26,27,28]],
               [[29,30,31],[32,33,34],[35,36,37]]])

print(arr3[0,0,:])
print(arr3[1,1,:])
print(arr3[2,2,:])
print('middle most:',arr3[1,1,1])
print(arr3[1,:,:])                   # access horizontal middle column
print(arr3[:,1,:])                   # access vertical middle column
print('middle list:',arr3[1,1,:])    

print(arr3[(0,0,0),(1,1,1),(2,2,2)])                        # ---ask? what it means---

[11 12 13]
[23 24 25]
[35 36 37]
middle most: 24
[[20 21 22]
 [23 24 25]
 [26 27 28]]
[[14 15 16]
 [23 24 25]
 [32 33 34]]
middle list: [23 24 25]
[16 16 16]
