### Numpy lec-11: Iterating Numpy Arrays

In [1]:
import numpy as np

In [2]:
# Iterating Numpy array  -using for loop
# iterating 1D array
arr1=np.arange(6)
for i in arr1:
    print(i)
print(arr1)

0
1
2
3
4
5
[0 1 2 3 4 5]


In [3]:
# iterating 2D array
arr2=np.arange(6).reshape(2,3)
print(arr2)

for i in arr2:        # to iterate rows of 2D array
    print(i)
for i in arr2:        # to iterate elements of 2D array
    for j in i:
        print(j)

[[0 1 2]
 [3 4 5]]
[0 1 2]
[3 4 5]
0
1
2
3
4
5


In [4]:
# iterating 3D array
arr3=np.arange(1,9).reshape(2,2,2)
print(arr3,'dimension:',arr3.ndim)

# iterating rows in 3D array
for i in arr3:                 
    print(i)
# iterating each rows of rows in 3D array  
for i in arr3:                 
    for j in i:
        print(j)
# iterating each elements of 3D array
for i in arr3:                 
    for j in i:
        for k in j:
            print(k) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] dimension: 3
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[1 2]
[3 4]
[5 6]
[7 8]
1
2
3
4
5
6
7
8


In [ ]:
# Iterating Numpy array           -using nditer()
# Efficient multi-dimensional iterator object to iterate over arrays
    '# syntax: np.nditer(arr_name)
    
# Docstring:  
np.nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

In [5]:
# lets try this
arr3=np.arange(1,9).reshape(2,2,2)
for i in np.nditer(arr3):
    print(i)

1
2
3
4
5
6
7
8


In [7]:
# Numpy array elements iteration with index number  -using ndenumerate()

# Multidimensional index iterator -1D,2D,3D....
    '# syntax: np.ndenumerate(arr_name)
    
arr3=np.arange(1,9).reshape(2,2,2)
print(' index: ','element:')

for i,e in np.ndenumerate(arr3):
    print(i,'-',e)

 index:  element:
(0, 0, 0) - 1
(0, 0, 1) - 2
(0, 1, 0) - 3
(0, 1, 1) - 4
(1, 0, 0) - 5
(1, 0, 1) - 6
(1, 1, 0) - 7
(1, 1, 1) - 8


### Numpy lec-12: Copy vs View in Numpy Arrays

In [ ]:
# Difference b/w copy and view
- copy owns the data                     -view does not owns the data
- copy of an array is a new array        -view of an array is original array
- changes made in copy does not
  reflect in original array              -changes made in view will affect the original and vice versa
# use:
- when dont wants any change in original  -when required to change original as well as duplicate

In [8]:
# Copy in Numpy Arrays
# syntax: np.copy(arr_name, order='K') -return an array copy of the given object
# syntax: arr_name.copy() -return a copy of the array
    
arr_1=np.array([1,2,3,4,5])
copy=arr_1.copy()
 
arr_1[2]=50                  # now change the data and check (changes only in one)
print('Array:',arr_1)
print('Copy:',copy)

Array: [ 1  2 50  4  5]
Copy: [1 2 3 4 5]


In [9]:
# View in Numpy Arrays
# syntax: arr_name.view()    -new view of array with the same data

arr_2=np.array([9,8,7,6,5])
view=arr_2.view()

arr_2[2]=50                  # now change the data and check (changed in both)
print('Array:',arr_2)
print('View:',view)

Array: [ 9  8 50  6  5]
View: [ 9  8 50  6  5]


### Numpy lec-13: Join & Split in Numpy Arrays

In [ ]:
# Join function in Numpy Arrays   -using concatenate()

# np.concatenate() -join a sequence of arrays along an existing axis
    syntax: np.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
- joining means putting contents of two or more arrays in a single array
- while joining no of elements should be same which are to be joined

# NOTE:
    column wise(axis=0): pahle array ke column ke niche 2nd array ka column
    row wise(axis=1): pahle array ke row me stack hoga 2nd array ka row

In [10]:
# joining 1D array     
arr1=np.array([9,8,7,6])
arr2=np.array([1,2,3,4])
arr=np.concatenate((arr1,arr2))
print(arr)

[9 8 7 6 1 2 3 4]


In [11]:
# joining 2D array
arr1=np.array([[9,8],[7,6]])
arr2=np.array([[1,2],[3,4]])
print(arr1)
print(arr2)
print('..........column wise')
arr=np.concatenate((arr1,arr2),axis=0)    # column wise concatenation
print(arr)
print('..........row wise')
arr=np.concatenate((arr1,arr2),axis=1)    # row wise concatenation
print(arr)

[[9 8]
 [7 6]]
[[1 2]
 [3 4]]
..........column wise
[[9 8]
 [7 6]
 [1 2]
 [3 4]]
..........row wise
[[9 8 1 2]
 [7 6 3 4]]


In [12]:
# joining 3D array
arr1=np.array([[[9,8]],[[7,6]],[[5,4]]])
arr2=np.array([[[1,2]],[[3,4]],[[5,6]]])
print(arr1)
print(arr2)
print('..........column wise')
arr=np.concatenate((arr1,arr2),axis=0)    # column wise concatenation
print(arr)
print('..........row wise')
arr=np.concatenate((arr1,arr2),axis=1)    # row wise concatenation
print(arr)

[[[9 8]]

 [[7 6]]

 [[5 4]]]
[[[1 2]]

 [[3 4]]

 [[5 6]]]
..........column wise
[[[9 8]]

 [[7 6]]

 [[5 4]]

 [[1 2]]

 [[3 4]]

 [[5 6]]]
..........row wise
[[[9 8]
  [1 2]]

 [[7 6]
  [3 4]]

 [[5 4]
  [5 6]]]


In [ ]:
# Join function in Numpy Arrays      -using stack
# np.stack() -join a sequence of arrays along a new axis
    syntax: np.stack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind')
# stack types:    
    syntax: np.hstack(tup, *, dtype=None, casting='same_kind')    -stack arrays horizontally (new column me stack hoga)
    syntax: np.vstack(tup, *, dtype=None, casting='same_kind')    -stack arrays vertically (new row me stack hoga)
    syntax: np.dstack(tup)                                        -stack arrays in sequence depth wise (along third axis)
        
# Note: 
- stack with axis=0 is same as np.vstack()
- stack with axis=1 is same as np.dstack()

In [ ]:
# Docstring:
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
hstack : Stack arrays in sequence horizontally (column wise).
vstack : Stack arrays in sequence vertically (row wise).
dstack : Stack arrays in sequence depth wise (along third dimension).

In [13]:
# joining 1D array   -using stack
arr1=np.array([9,8,7,6])
arr2=np.array([1,2,3,4])
arr=np.stack((arr1,arr2),axis=0)      # column wise stack
print(arr)
arr=np.stack((arr1,arr2),axis=1)      # row wise stack
print(arr)

[[9 8 7 6]
 [1 2 3 4]]
[[9 1]
 [8 2]
 [7 3]
 [6 4]]


In [14]:
# joining 1D array     -using stack horizontally, vertically, along height(3rd axis)
arr1=np.array([9,8,7,6])
arr2=np.array([1,2,3,4])
arr=np.hstack((arr1,arr2))    # stacked horizontally  -along row  
print(arr)
arr=np.vstack((arr1,arr2))    # stacked vertically    -along column
print(arr)
arr=np.dstack((arr1,arr2))    # stacked along height
print(arr)

[9 8 7 6 1 2 3 4]
[[9 8 7 6]
 [1 2 3 4]]
[[[9 1]
  [8 2]
  [7 3]
  [6 4]]]


In [ ]:
# similarly: try for this
# joining 2D array     -using stack horizontally, vertically, along height(3rd axis)

# joining 3D array     -using stack horizontally, vertically, along height(3rd axis)


In [ ]:
# Split function in Numpy Arrays         -using split
- to split/break an array into multiple sun-arrays
- we get splitted array in form of list data type
- so we can access any sub-array by its index number
    'syntax: np.split(arr_name, indices_or_sections, axis=0)
    'syntax: np.array_split(arr_name, indices_or_sections, axis=0)

In [ ]:
# Docstring:
array_split : Split an array into multiple sub-arrays of equal or
              near-equal size.  Does not raise an exception if
              an equal division cannot be made.
hsplit : Split array into multiple sub-arrays horizontally (column-wise).
vsplit : Split array into multiple sub-arrays vertically (row wise).
dsplit : Split array into multiple sub-arrays along the 3rd axis (depth).

In [15]:
# lets try this
# splitting 1D array
arr1=np.array([1,2,3,4,5,6])
arr_sp=np.split(arr1,3)

print('splitted array:',arr_sp)          # split array in form of list
print('unpacking:',*arr_sp)              # unpacking of splitted array
print('1st splitted array:',arr_sp[0])   # to get particular array in splitted array use indexing

splitted array: [array([1, 2]), array([3, 4]), array([5, 6])]
unpacking: [1 2] [3 4] [5 6]
1st splitted array: [1 2]


In [16]:
# splitting 2D array
arr2=np.array([[9,8,7,6],
               [1,2,3,4]])
arr_sp=np.split(arr2,2)
print(arr_sp,'\n',*arr_sp,'\n',arr_sp[0])
print('.................')

# splitting 2D array   -along axis
arr2=np.array([[9,8,7,6],
               [1,2,3,4]])
arr_sp=np.split(arr2,4,axis=1)
print(arr_sp)                 # splitted array
print(*arr_sp)                # unpacking
print(arr_sp[0])              # accessing splitted array

[array([[9, 8, 7, 6]]), array([[1, 2, 3, 4]])] 
 [[9 8 7 6]] [[1 2 3 4]] 
 [[9 8 7 6]]
.................
[array([[9],
       [1]]), array([[8],
       [2]]), array([[7],
       [3]]), array([[6],
       [4]])]
[[9]
 [1]] [[8]
 [2]] [[7]
 [3]] [[6]
 [4]]
[[9]
 [1]]


In [ ]:
# similarly: try for this
# splitting 3D array
