### Numpy lec-17: Concept of Matrices in Numpy Arrays

In [1]:
import numpy as np

In [ ]:
# Matrix in Numpy Array
#                   matrix                             vs                  array
- It is 2D representation                                 - It is an extension of 2D matrix and can be multi-dimensional
- A matrix is a rectangular array or table of numbers,    - Arrays are a fundamental data structure, they are containers 
  symbols, or expressions, arranged in rows and columns     which are able to store more than one item at the same time
- which is used to represent a mathematical               - They are an ordered collection of elements 
  object or a property of such an object                    with every value being of the same data type

 syntax: np.matrix(data, dtype=None, copy=True)          np.array(object, dtype=None, *,copy=True,order='K',ndmin=0,like=None)

In [2]:
# creation of numpy matrix and numpy array
mat=np.matrix([[10,20,30],[90,80,70]])
print(mat,type(mat))

arr=np.array([[10,20,30],[90,80,70]])
print(arr,type(arr))

[[10 20 30]
 [90 80 70]] <class 'numpy.matrix'>
[[10 20 30]
 [90 80 70]] <class 'numpy.ndarray'>


In [ ]:
# Note:
- addition and substraction are performed directly in both matrix and array
- multiplication and division are performed directly in array only
- but multiplication and division are performed by dot function in matrix
- while performing operations must take care of broadcasting

In [3]:
# Arithmetic operation of matrix
mat1=np.matrix([[9,8,7],[6,5,4],[3,2,1]])
mat2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(mat1+mat2,'....matrix addition:')
print(mat1-mat2,'.....matrix substraction:')
print(mat1.dot(mat2),'....matrix multiplication:')    # for multiplication use dot(.) function

# Think what will happen if we unpack here

[[10 10 10]
 [10 10 10]
 [10 10 10]] ....matrix addition:
[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]] .....matrix substraction:
[[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]] ....matrix multiplication:


In [ ]:
# Matrix functions in Numpy Arrays
Transpose: -returns the transpose of the matrix
    'syntax: matrix_name.T   or   np.transpose(matrix_name)
    
Swapaxes:  -interchange two axes of an array
    'syntax: np.swapaxes(matrix_name, axis1, axis2)
    
Inverse:   -compute the (multiplicative) inverse of a matrix
    'syntax: np.linalg.inv(matrix_name)
    
Power:     -raise a square matrix to the (integer) power `n` -(A**2=A*A)
    'syntax: np.linalg.matrix_power(matrix_name, n)
        if n==0: Identity matrix
            n>0: Power matrix
            n<0: Inverse*Power
    
Determinate:-compute the determinant of an array
    'syntax: np.linalg.det(matrix_name)
    

In [4]:
# lets try this
mat1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat1,'........matrix')

print(np.transpose(mat1),'.......transpose')     # we can also use: matrix_name.T
print(np.swapaxes(mat1,0,1),'.......swapaxes')

[[1 2 3]
 [4 5 6]
 [7 8 9]] ........matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]] .......transpose
[[1 4 7]
 [2 5 8]
 [3 6 9]] .......swapaxes


In [3]:
# lets try this
mat2=np.matrix([[1,0,5],[2,1,6],[3,4,0]])
print(mat2,'..........matrix')

print(np.linalg.inv(mat2),'........inverse')
print(np.linalg.matrix_power(mat2,2),'.........positive power')
print(np.linalg.matrix_power(mat2,0),'.........power=0 => Identity matrix')
print(np.linalg.matrix_power(mat2,-2),'.........negative power')
print(np.linalg.det(mat2),'.........determinant')

[[1 0 5]
 [2 1 6]
 [3 4 0]] ..........matrix
[[-24.  20.  -5.]
 [ 18. -15.   4.]
 [  5.  -4.   1.]] ........inverse
[[16 20  5]
 [22 25 16]
 [11  4 39]] .........positive power
[[1 0 0]
 [0 1 0]
 [0 0 1]] .........power=0 => Identity matrix
[[ 911. -760.  195.]
 [-682.  569. -146.]
 [-187.  156.  -40.]] .........negative power
0.9999999999999967 .........determinant
